name: Build and Release

on:
  push:
    tags:
      - 'v*' 
  workflow_dispatch: 

jobs:
  build:
    name: Build for All Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build Binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        mkdir -p dist/${{ matrix.goos }}-${{ matrix.goarch }}
        go build -o dist/${{ matrix.goos }}-${{ matrix.goarch }}/radio_app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.goos }}-${{ matrix.goarch }}
        path: dist/${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/**/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automatic release for version ${{ github.ref_name }}.
        draft: false
        prerelease: false
