name: Build and Release GoWave

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build GoWave
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        env:
          GOOS: ${{ matrix.os == 'windows-latest' && 'windows' || (matrix.os == 'macos-latest' && 'darwin' || 'linux') }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -o dist/GoWave-${{ matrix.os }}-${{ matrix.goarch }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: GoWave-${{ matrix.os }}-${{ matrix.goarch }}
          path: dist/GoWave-${{ matrix.os }}-${{ matrix.goarch }}*

  release:
    name: Release GoWave
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
